### ISSUE TITLE
Issues with types not matching fastify itself

### ISSUE THREAD

**Issue by chriswiggins** [fastify/fastify-http-proxy#100]
## 🐛 Bug Report

From what I can tell, the upstream types for the request/reply interfaces in `fastify` have changed, which means that the types in `fastify-http-proxy` are no longer correct. I've tried to work out how to fix these myself, but I don't understand `fastify` well enough to make sure I'm not going to break anything. I tried removing  `RawServerBase` from the generic but the type check still fails with the **too wide** issue. Happy to be pointed in the right direction to fix it properly!

## To Reproduce

Do an `npm run typescript` in this project

## Expected behavior

Tests to pass

## Actual behaviour

```
% npm run typescript

> fastify-http-proxy@4.0.2 typescript /Users/chris/development/fastify-http-proxy
> tsd


  test/index.test-d.ts:21:4
  ✖  21:4   Parameter type IncomingMessage | Http2ServerRequest is declared too wide for argument type IncomingMessage.
  ✖  25:4   Parameter type IncomingMessage | Http2ServerRequest is declared too wide for argument type IncomingMessage.

  index.d.ts:18:28
  ✖  18:28  Type RawServerBase does not satisfy the constraint RouteGenericInterface.
  Type Server has no properties in common with type RouteGenericInterface.
  ✖  23:28  Type RawServerBase does not satisfy the constraint RouteGenericInterface.
  Type Server has no properties in common with type RouteGenericInterface.

  4 errors
```

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Tests are passing in CI, what version of Fastify are you testing this against?

**Comment by chriswiggins** [comment]
CI as far as I can tell for this project doesn't run any type-tests?

All I did to get that error was:

```shell
git clone https://github.com/fastify/fastify-http-proxy.git fhp
cd fhp
npm install
npm run typescript
```

Presuming that `npm run typescript` is the correct way to be testing the types?

**Comment by mcollina** [comment]
Oooh `npm run typescript` was not added to CI. Sigh.

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by chriswiggins** [comment]
Absolutely Matteo! I’ll try to get to it in the next few days

**Comment by mcollina** [comment]
Thanks!

**Comment by chriswiggins** [comment]
Closing as PR has been merged
