### ISSUE TITLE
Option types not in sync with fastify-reply-from

### ISSUE THREAD

**Issue by gyszalai** [fastify/fastify-http-proxy#102]
## 🐛 Bug Report

Typescript interface `FastifyHttpProxyOptions` does not extend `FastifyReplyFromOptions` from module `fastify-reply-from`, so it's not possible to specify e.g. the `http` option in `fastify-http-proxy`.

## To Reproduce

```js
    fastify.register(proxy, {
        upstream: upstreamUrl,
        prefix,
        http2: false,
        http: {
          requestOptions: {
            timeout: 20000
          }
        }
    })
```

## Expected behavior

It is expected to be compiled without errors, but I get the following error:
```
Object literal may only specify known properties, but 'http' does not exist in type '{ upstream: string; prefix?: string | undefined; rewritePrefix?: string | undefined; http2?: boolean | undefined; proxyPayloads?: boolean | undefined; preHandler?: ((request: FastifyRequest<IncomingMessage | Http2ServerRequest, DefaultQuery, DefaultParams, DefaultHeaders, any>, reply: FastifyReply<...>, next: (err?:...'. Did you mean to write 'http2'?
```

## Your Environment

- *node version*: 14
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gyszalai** [comment]
Of course! Hopefully I can do it today.

**Comment by gyszalai** [comment]
@mcollina is it intentional that the `http2` option is only `boolean` in `fastify-http-proxy` whereas it is `Http2Options | boolean` in `fastify-reply-from`?

**Comment by mcollina** [comment]
> is it intentional that the http2 option is only boolean in fastify-http-proxy whereas it is Http2Options | boolean in fastify-reply-from?

I don't think so!

**Comment by gyszalai** [comment]
OK, I'll remove the http2 option from fastify-http-proxy.
