### ISSUE TITLE
using undici pipelining + pool might not be a good idea?

### ISSUE THREAD

**Issue by ronag** [fastify/fastify-http-proxy#104]
Different clients could block each other. Should probably have one connection/pool per remote client? DDoS risk otherwise? Or maybe even one connection per request and just re-use them, like node core agent class does? At least for requests that contain a body. Though receiving headers could also be head of line blocking.

i.e. if you have a pipeline that is serving both fast and slow clients, the slow clients would block the fast ones.

**Comment by mcollina** [comment]
It would suffer from head of line blocking. Creating a smarter algorithm that use pipeline for GET and avoid it for POST would be interesting.
