### ISSUE TITLE
Can't add route on root while using this plugin

### ISSUE THREAD

**Issue by pearofducks** [fastify/fastify-http-proxy#118]
## 🐛 Bug Report

If I try to register a handler on root, and use this plugin; Fastify throws `AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/'`.

## To Reproduce

```js
const fastify = require('fastify')()
const proxy = require('fastify-http-proxy')

;(async () => {
  fastify.get('/', (_, reply) => reply.send('hello'))
  fastify.register(proxy, { upstream: 'http://localhost:8081', path: '/llama', rewritePrefix: '/llama' })
  await fastify.listen(8080, '0.0.0.0')
})()
```

The same as above with dependencies and such ready - https://github.com/pearofducks/fastify-proxy-repro

## Expected behavior

Able to have a route on root, and add a proxy.

## Your Environment

- *node version*: `v15.2.0`
- *os*: Mac - `11.0.1`

```
  "dependencies": {
    "fastify": "^3.8.0",
    "fastify-http-proxy": "^4.0.4"
  }
```

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-http-proxy/blob/aa490444beb783f60113145c3e151378fbbcd5ec/index.js#L53-L58 - I think we'll need to put those behind an option. Would you like to send a PR?

**Comment by pearofducks** [comment]
Just the `/` handler? If I remove the `/` handlers (both the `.get` and the `.route`) - then I'm still unable to register two proxies because of the `/*` handlers.

```
const fastify = require('fastify')()
const proxy = require('fastify-http-proxy')

;(async () => {
  await fastify.get('/', (_, reply) => reply.send('hello'))
  await fastify.register(proxy, { upstream: 'http://localhost:8081', path: '/llama/bar', rewritePrefix: '/llama/bar' })
  await fastify.register(proxy, { upstream: 'http://localhost:8082', path: '/llama/foo', rewritePrefix: '/llama/foo' })
  await fastify.listen(8080, '0.0.0.0')
})()
```

`AssertionError [ERR_ASSERTION]: Method 'DELETE' already declared for route '/*'`

**Comment by mcollina** [comment]
What does ` path: '/llama/bar'` do? Maybe you expect it to be `prefix`?

**Comment by pearofducks** [comment]
Yes, thanks, whew I was losing my mind there for a second.

**Comment by pearofducks** [comment]
Yeah, that `path` was the root issue with the first issue too. Sorry for the noise here, thanks for spotting that.
