### ISSUE TITLE
fastify-http-proxy does not respect 302 redirects

### ISSUE THREAD

**Issue by vorillaz** [fastify/fastify-http-proxy#124]
## 🐛 Bug Report
Hey, thanks for this amazing project. I have some trouble when the upstream servers are triggering some redirects. It seems that the proxy is prefixing the 

## To Reproduce

```js
const Fastify = require('fastify')
const proxy = require('fastify-http-proxy')

const server = Fastify()
const upstream = Fastify()


// Declare a route
const Fastify = require('fastify');
const proxy = require('fastify-http-proxy');

const server = Fastify();
const upstream = Fastify();

// Declare a route
upstream.get('/', async (request, reply) => {
  return reply.redirect(302, 'https://google.com');
});

upstream.get('/foo', async (request, reply) => {
  return reply.send({hello: 'world'});
});

upstream.listen(3001);

server.register(proxy, {
  upstream: 'http://localhost:3001',
  prefix: '/bar'
});

server.listen(3000);

```

## Expected behavior

Visiting `http://localhost:3000/bar/foo` the proxy works as expected, visiting `http://localhost:3000/bar` a new redirect was triggered to `/barhttps://google.com`

## Your Environment

- *node version*: 14
- *fastify version*: 3.9.2
- *os*: Mac

**Comment by mcollina** [comment]
Good spot!! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by vorillaz** [comment]
@mcollina Off course, I would love to work on this one. I jumped through the code but I couldn't find any status code involved in order to detect 3xx redirects. `rewriteHeaders` seems a good place to get started but I can't detect if the request is a redirect.
Any help or hints will be highly appreciated.

**Comment by mcollina** [comment]
The bug is in rewriteHeaders. There is a replace in there that should not be applied in this case.
