### ISSUE TITLE
Improve typing of `replyOptions`

### ISSUE THREAD

**Issue by hmaurer** [fastify/fastify-http-proxy#126]
## 🚀 Feature Proposal

Give a more precise type to `replyOptions` (https://github.com/fastify/fastify-http-proxy/blob/0f7b501158cb7a4c5d27ec9fb653a2156421284d/index.d.ts#L25). At the moment the type is `Object`, aka untyped.

## Motivation

It'd appear that `replyOptions` conforms to the `FastifyReplyFromHooks` type (https://github.com/fastify/fastify-reply-from/blob/0b34fe66ac0c8814dc912020014538bd846d9f76/index.d.ts#L32), so perhaps this package should import and use this type?

There might have been a good reason why the person who wrote the code left `replyOptions` loosely typed though. Perhaps it doesn't quite conform to `FastifyReplyFromHooks`. I hope a maintainer can shed some light on this!

PS: thanks for the amazing work on this library <3

**Comment by hmaurer** [comment]
I'd be keen on opening a PR for this if a maintainer confirms that there's no underlying reason to not type this property.

**Comment by mcollina** [comment]
Go for it!
