### ISSUE TITLE
Based on prefix, proxy to different paths within same host

### ISSUE THREAD

**Issue by dlbrown06** [fastify/fastify-http-proxy#13]
Am I able to register a proxy like this?

```
  fastify.register(proxy, {
    upstream: 'https://hostname.com/api/v1',
    prefix: '/api',
    http2: false
  });

  fastify.register(proxy, {
    upstream: 'https://hostname.com/api/v1',
    prefix: '/api/v1',
    http2: false
  });
```

From what I can tell, it looks like both prefixes redirect to just the hostname excluding the `api/v1` path.

So if I call `https://beforeproxy.com/api/this-endpoint` proxies to `https://hostname.com/this-endpoint`.

**Comment by mcollina** [comment]
Yes, it should work. Are you having some trouble with these options?

**Comment by dlbrown06** [comment]
Yeah, it appears that in the above example, it is just proxying to `https://hostname.com` and not `https://hostname.com/api/v1` that is defined in the upstream. Is that the expected behavior?

**Comment by dlbrown06** [comment]
@mcollina We can close this. I'm getting around it by using the `beforeHandler` to alter the url to go to the correct url rather than having to setup multiple proxies.
