### ISSUE TITLE
Proxy server returns a 308 when placed behind a rewriteUrl fastify server

### ISSUE THREAD

**Issue by lanyusan** [fastify/fastify-http-proxy#145]
## 🐛 Bug Report

I have a server that rewrite a request `site-1.localhost` to `localhost/site-1`. Then I registerred the proxy plugin as 
```
      fastify.register(fastifyProxy, {
        upstream,
        prefix: 'site-1', // optional
        http2: false, // optional
      })
```

A request of `site-1.localhost` is responded with a 308 redirect to `localhost/site-1/site-1`
## To Reproduce

Start fastify server:

```
  const fastify = fastify({
    logger: {
      level: isProduction ? 'error' : 'info',
    },
    ...settings.fastify,
    rewriteUrl: function (req) {
       const subsite = getSubsite(req.headers.host) // get site-1 from site-1.localhost
       return subsite + req.url
    },
  })
```

Register proxy:

```
      fastify.register(fastifyProxy, {
        upstream,
        prefix: 'site-1', // optional
        http2: false, // optional
      })
```

## Expected behavior

Respond with proxyed page but got 308.

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=3
- *os*: Linux

**Comment by mcollina** [comment]
Could you please upload a complete, runnable example to reproduce your problem?

**Comment by lanyusan** [comment]
The problem is repeatable in my production setup but when I try to reproduce it in a more simple proxy server config, everything is fine.

I will investigate it more to see if it is my code's problem or certain condition needs to be met for it to repeat.

**Comment by mcollina** [comment]
let us know!
