### ISSUE TITLE
fastify-http-proxy not removing prefix

### ISSUE THREAD

**Issue by BlazingAsher** [fastify/fastify-http-proxy#152]
## 🐛 Bug Report

When using fastify-http-proxy, the library does not remove the prefix from the request URL before proxying it to the upstream.

## To Reproduce

```js
fastify.register(require('fastify-http-proxy'), {
    upstream: 'example.com',
    prefix: 'testprefix'
 });

fastify.listen(3005, '0.0.0.0', function (err, address) {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
});
```

For the request `/testprefix/users`, the upstream receives `/testprefix/users` instead of `/users`.

## Expected behavior

The prefix should be removed from the URL before proxying it to the upstream.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.14.2
- *os*: Windows

**Comment by BlazingAsher** [comment]
Looking through the code, it seems line 185 should be `fastify.prefix` instead of `this.prefix`.

**Comment by mcollina** [comment]
makes sense! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
