### ISSUE TITLE
Plugin must be a function or a promise. TypeScript project.

### ISSUE THREAD

**Issue by wesbragagt** [fastify/fastify-http-proxy#169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.1

### Plugin version

6.0.0

### Node.js version

15

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

I followed the documentation steps for the fastify-cli and fastify-http-proxy in order to implement the plugin and I keep getting the same error. Error: plugin must be a function or a promise.

### Steps to Reproduce

- Start a Fastify project using `fastify generate project --lang=ts`
- cd project && npm install
- paste the following code under app.ts
```javascript
import { join } from 'path'
import AutoLoad, { AutoloadPluginOptions } from 'fastify-autoload'
import { FastifyPluginAsync } from 'fastify'
import fastifyHttpProxy from 'fastify-http-proxy'

// look into implementing this package https://github.com/fastify/fastify-http-proxy

export type AppOptions = {
    // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
    // Place here your custom code!
    fastify.register(fastifyHttpProxy, {
        upstream: 'https://jsonplaceholder.typicode.com/todos',
        prefix: '/todos'
    })
    // Do not touch the following lines

    // This loads all plugins defined in plugins
    // those should be support plugins that are reused
    // through your application
    void fastify.register(AutoLoad, {
        dir: join(__dirname, 'plugins'),
        options: opts
    })

    // This loads all plugins defined in routes
    // define your routes in one of these
    void fastify.register(AutoLoad, {
        dir: join(__dirname, 'routes'),
        options: opts
    })
}

export default app
export { app }
```

- npm run dev

### Expected Behavior

You should get an error in the terminal saying "Error: plugin must be a function or a promise"

![image](https://user-images.githubusercontent.com/40429790/126352004-d8981b2c-4603-4ea0-9651-b59c8909d23e.png)

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by climba03003** [comment]
It is not Typescript error but an `avvio` error. I think it is cause by the `fastify-autoload`. Some of the files inside either folder `plugins` or `routes` do not export a correct function.

**Comment by wesbragagt** [comment]
Still the same issue without Autoload 
![image](https://user-images.githubusercontent.com/40429790/126422768-d12ec1b7-ee0f-4434-b500-b699d2d16691.png)

**Comment by climba03003** [comment]
> 
> 
> Still the same issue without Autoload
> ![image](https://user-images.githubusercontent.com/40429790/126422768-d12ec1b7-ee0f-4434-b500-b699d2d16691.png)

Check the content in `./modules/db` and `./modules/routes/vehicles`.

**Comment by wesbragagt** [comment]
Pretty standard stuff just the plug-in structure. I tried a project without typescript and couldn't get the error. Must be something with Autoload or the types for this library.

**Comment by climba03003** [comment]
@wesbragagt Can you check if `v6.0.1` solve your problem?

**Comment by wesbragagt** [comment]
Man, that did it! I was trying to replicated in a repo so I could share with you guys. Appreciate the support!
