### ISSUE TITLE
Allow specifying constraints

### ISSUE THREAD

**Issue by dominik-korsa** [fastify/fastify-http-proxy#181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Allow specifying custom [constraints](https://www.fastify.io/docs/latest/Routes/#constraints) on routes matched by the proxy

https://github.com/fastify/fastify-http-proxy/blob/master/index.js#L176-L182

### Motivation

This would be a potential solution for the problem described in #129 

### Example

```ts
import FastifyHttpProxy from 'fastify-http-proxy';
import Fastify from 'fastify';

const fastify = Fastify();

fastify.register(FastifyHttpProxy, {
  upstream: `http://localhost:3000`,
  constraints: { version: '1.2.0' },
});

fastify.listen();
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by dominik-korsa** [comment]
I'm trying to do that right now
