### ISSUE TITLE
Debug entire outgoing upstream request

### ISSUE THREAD

**Issue by ndmgrphc** [fastify/fastify-http-proxy#189]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Need a way to access and review the complete upstream request to debug.

### Motivation

Need a way to access and review the complete upstream request to debug.

### Example

onUpstreamRequest(request)...

**Comment by Firanolfind** [comment]
I find this feature very useful as well
