### ISSUE TITLE
Proxying unix sockets?

### ISSUE THREAD

**Issue by MatthiasGrandl** [fastify/fastify-http-proxy#194]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

6.2.1

### Node.js version

17.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0.1

### Description

It seems as if it's not possible to proxy unix sockets?

```js
{
upstream: 'unix:///tmp/ttyd.sock', // no luck with this
upstream: 'http://localhost:7681', // this works
}
```

note: both of the above are the exact same server

### Steps to Reproduce

Try proxying any unix socket. It doesn't work.
Returns: `{"statusCode":500,"code":"ERR_INVALID_URL","error":"Internal Server Error","message":"Invalid URL"}`

### Expected Behavior

Proxying a unix socket should work. https://github.com/http-party/node-http-proxy handles this usecase fine.

**Comment by MatthiasGrandl** [comment]
Nevermind, figured it out:

`unix+http://${encodeURIComponent("/tmp/ttyd.sock")}` works

**Comment by MatthiasGrandl** [comment]
Mhm but proxying websockets from a unix socket doesn't seem to work...

`ws+unix://${encodeURIComponent("/tmp/ttyd.sock")}`

It just doesn't seem to do anything at all.

**Comment by Eomm** [comment]
The support for ws is not featured complete https://github.com/fastify/fastify-http-proxy#todo

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by MatthiasGrandl** [comment]
@Eomm I tried to figure it out for a little bit. I figured out that the URL that `ws` expects needs to look like `ws+unix:///tmp/ttyd.sock:/ws` note the `:` that separates the base from the `path`. After fixing the URL the websocket opens as expected, but I can't get anything to actually proxy, so I gave up for now and went back to `http-proxy`.
