### ISSUE TITLE
Unable to get dynamic routes

### ISSUE THREAD

**Issue by phwang4** [fastify/fastify-http-proxy#199]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.0

### Plugin version

6.2.1

### Node.js version

12.13.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I have a fastify server that's pointing to two "backend" fastify servers and I'd like to generate a random number that is then used to decide which backend to route to.

Currently it only works the first time, and I'm unable to override the upstream afterwards.

### Steps to Reproduce

```
server.register(require('fastify-http-proxy'), {
  upstream: '',
  replyOptions: { 
    getUpstream: (originalReq, base) => {
      if (Math.random() < 0.5) {
        console.log(`setting base to backend1`)
        return `http://localhost:${backend1Port}`
      } else {
        console.log(`setting base to backend2`)
        return `http://localhost:${backend2Port}`
      }
    },
    disableCache: true,
    cacheURLs: 0,
  },
})
```

### Expected Behavior

When the method above sets the base/upstream to backend 1, I'll output a message from backend 1, and when it sets the base/upstream to backend 2, I'll output a message from backend 2.

**Comment by mcollina** [comment]
I think this information is cached. 
Would you like to send a Pull Request to address this feature? Remember to add unit tests.

**Comment by climba03003** [comment]
I think he is just put the option in wrong place.

`disableCache` and `cacheURLs` is the option for `fastify-reply-from` not `request.from`. So, it should not place inside `replyOptions`.

```js
server.register(require('fastify-http-proxy'), {
  upstream: '',
  replyOptions: { 
    getUpstream: (originalReq, base) => {
      if (Math.random() < 0.5) {
        console.log(`setting base to backend1`)
        return `http://localhost:${backend1Port}`
      } else {
        console.log(`setting base to backend2`)
        return `http://localhost:${backend2Port}`
      }
    }
  },
  disableCache: true,
  cacheURLs: 0,
})
```

**Comment by phwang4** [comment]
@climba03003 Thank you, this was it.
