### ISSUE TITLE
Failure with "Promise may not be fulfilled with 'undefined'

### ISSUE THREAD

**Issue by pradipmukhopadhyay** [fastify/fastify-http-proxy#229]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.5

### Plugin version

6.2.1

### Node.js version

16.5.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I have posted the same question to [stackoverflow here](https://stackoverflow.com/questions/71021755/fastify-http-proxy-failure-with-promise-may-not-be-fulfilled-with-undefined)

I am using the fastify with fastify-http-proxy with the following configuration:

```js
const proxy = require('fastify-http-proxy');
fastify.register(proxy, {
    upstream: "https://myendpoint/occm/api/azure",
    prefix: '/azure',
    onResponse: (request, reply, res) => {
        console.log('Inside onResponse')
        reply.send('New body of different length');
    },
    onError: (reply, error) => {
        console.log('Inside onError')
        reply.send(`My Error: ${error}`);
    },
    replyOptions: {
		rewriteRequestHeaders: (originalRequest, headers) => {
            console.log('Inside rewriteRequestHeaders')
			return {
				...headers,
			};
		},
	},
});
```

I have configured a fastify route as this:

```js
 fastify.route({
        method: 'GET',
        url: `/azure/vsa/working-environments`,
        schema: {
            description: 'Trying out',
            tags: ['notifications'],
            security: [{
                authorization: []
            }],
            params:{
                title: "Working Env GET",
                description:'Trying out...',
                type: 'object',
                example: 'No input',
                properties: {
                    'accountId': {
                        description: "Account ID",
                        type: 'string'
                    },
                },
            }
        },
        handler: async (request, reply) => {
        }
```

I am calling it as:

> GET http://localhost:xxxx/azure/vsa/working-environments

Basically I would like to proxy the request to this endpoint:

> https://myendpoint/occm/api/azure/vsa/working-environments

Now whenever I am running it, getting this error:

```
{"level":30,"time":1644249539394,"pid":12100,"hostname":"pradipm02-PC","requestId":"Q3T9RjI11N","req":{"method":"GET","url":"/azure/vsa/working-environments","hostname":"localhost:8092","remoteAddress":"127.0.0.1","remotePort":63308},"msg":"incoming request"}
{"level":50,"time":1644249540657,"pid":12100,"hostname":"pradipm02-PC","requestId":"Q3T9RjI11N","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Users\\pradipm\\clients\\CloudManager\\cm_2\\occm\\service-infra\\notifications\\node_modules\\fastify\\lib\\wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}

```

Any of the console.log in the rewriteRequestHeaders, onReponse, onError are not showing up. 

Any help is appreciated.

### Steps to Reproduce

Configure per the above fastify-http-proxy configuration.

### Expected Behavior

The error should not appear and the proper proxying should happen.

**Comment by Eomm** [comment]
Where did you define the `url: `/azure/vsa/working-environments`,` endpoint?
Why there is a `schema.params` but there is not any path parameter?
Why your `handler` is empty - aka it is returning `undefined`?

**Comment by pradipmukhopadhyay** [comment]
Hi,

The URL backend is actually in the upstream in `https://myendpoint/occm/api/azure`. So the route declaration of ` url: `/azure/vsa/working-environments` is in the route as provided above.

I removed the schema.param - still same issue.

I don't want to handle anything. What I want simply is that: any request coming to `http://localhost:xxxx/azure/vsa/working-environments`, want it to proxy to `https://myendpoint/occm/api/azure/vsa/working-environments`. That's it. All the payload, headers, response I just want to pass on/receive as-is. Do not want to do any processing.

**Comment by mcollina** [comment]
You might want to use fastify-reply-from instead. It's built for exactly that purpose.

**Comment by pradipmukhopadhyay** [comment]
OK. 
Let me understand it a bit. 
If I use the [fastify-reply-from](https://github.com/fastify/fastify-reply-from), do you mean that in the handler(..) of the proxy route, I just need to mention reply.from('/azure'). And the proxy (which is of fastify-reply-from), I need to register base: 'https://myendpoint/occm/api/azure'? Something like:

**Comment by mcollina** [comment]
You are not returning anything from the async function. Just removing `async` would do.

```js
proxy.route({
        method: 'GET',
        url: `/azure/vsa/working-environments`,
        schema: {
            description: 'Trying out',
            tags: ['notifications'],
        },
        handler: (request, reply) => {
            reply.from('/vsa/working-environments'); 
        }
    });
```

Alternatively, you can:

```js
proxy.route({
        method: 'GET',
        url: `/azure/vsa/working-environments`,
        schema: {
            description: 'Trying out',
            tags: ['notifications'],
        },
        handler: async (request, reply) => {
            reply.from('/vsa/working-environments'); 
				  return reply
        }
    });
```

**Comment by pradipmukhopadhyay** [comment]
Appreciated. Thanks!

**Comment by pradipmukhopadhyay** [comment]
One question though. This is for `GET`. 
Will this strategy works for other REST verbs like `POST`, `PATCH`, `DELETE` etc. also that takes a payload? I meant the `handler` portion. Would the default behavior of proxy to relay the payload as-is? Just confirming.
