### ISSUE TITLE
How to dynamically set upstream by request host (tenant)

### ISSUE THREAD

**Issue by edson-nascimento** [fastify/fastify-http-proxy#232]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm developing a multi tenant api where:
Each tenant will have a different upstream url that must be dynamically set after identification.
I do the tenant identification by domain hostname.

```typescript
async function getProxyUrlByTenant(request: FastifyRequest): Promise<string> {
  const tenant = await getTenantByHost(request.hostname);

  if (!tenant) throw new Error('Unauthorized');

  return tenant.apiUrl;
}

// Tenant routes
export async function proxyRoutes(server: FastifyInstance) {
  server.get('/status', async () => {
    return {
      status: 'active',
      at: new Date().toISOString(),
    };
  });

  // Proxy routes
  server.register(proxy, {
    upstream: await getProxyUrlByTenant(/* how get request here ? */),
    prefix: '/proxy',
  });
}
```

**Comment by KaKi87** [comment]
How did you implement it ? Thanks

**Comment by irg1008** [comment]
Why close it without explanation????!!!!!

**Comment by edson-nascimento** [comment]
I didn't continue using `fastify-http-proxy`, I solved my problem with https://github.com/fastify/fastify-reply-from

Example:
```js
 server.all('/*', options, async (request, reply) => {
    return reply.from(getProxyUrlByTenant(request) + request.url);
  });

**Comment by irg1008** [comment]
Thank you, sorry for being harsh! I was not expecting for you to reply. Worked for my use case!!
