### ISSUE TITLE
Versions of this package do not match on GitHub vs. npm

### ISSUE THREAD

**Issue by Trott** [fastify/fastify-http-proxy#242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

npm has version 6.3.0 but that version does not exist in GitHub packages. There is also no 6.3.0 tag in the GitHub repo.

GitHub packages has 7.0.0 but that version does not exist in npm

6.3.0 does not contain the types files that is included in 6.2.2 so it might break a lot of folks using TypeScript. (That's how I noticed.)

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify-http-proxy/pull/238
