### ISSUE TITLE
Does it supports Fastify 4?

### ISSUE THREAD

**Issue by yohayg** [fastify/fastify-http-proxy#262]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, What is the recommended Fastify version, and does it supports Fastify v4?

Doc should be updated accordingly.

Thanks,

**Comment by mcollina** [comment]
Good spot! https://github.com/fastify/fastify-http-proxy/pull/263
