### ISSUE TITLE
noobie clarification - unauthorized users 

### ISSUE THREAD

**Issue by dsplog** [fastify/fastify-http-proxy#267]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Noobie question coming to mind is :

- url of the proxy server is exposed in the javascript
- given so, unauthorised users can still call the proxy server api and get results.
How do we protect against that ?

**Comment by mcollina** [comment]
I don't understand your questions, could you expand?

**Comment by dsplog** [comment]
Ah, what I meant to ask was : 
- have seen example of using proxy server to avoid storing api key in the frontend code. 

- An article stating similar thought at https://simonplend.com/how-to-securely-call-an-authenticated-api-from-your-front-end/

But what I did not follow is - won't rogue users still be able to call the proxy server api and get the results. Are there hooks to protect against this.

**Comment by Uzlopak** [comment]
I also dont see in your link how it is implementing a "securely" access. So yes. A rogue user could do malice with your proxy.

**Comment by mcollina** [comment]
I would recommend to ask @simonplend who wrote that article.

FWIW I think the article is clear in how things are protected and contains a better answer than I could give.

**Comment by simonplend** [comment]
I've replied on [this issue](https://github.com/simonplend/example-nodejs-api-proxy-server/issues/1#issuecomment-1231421608).
