### ISSUE TITLE
Variable prefixed path feature & formbody support content-type

### ISSUE THREAD

**Issue by alchristleo** [fastify/fastify-http-proxy#272]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi I noticed this pr https://github.com/fastify/fastify-http-proxy/pull/266 fix the issue with variable prefix case, but it is released on version 8, do you mind adding this fix on version 7.x? Thanks

Second question, do you mind to give an example on how to integrate this with https://github.com/fastify/fastify-formbody plugin, to support `application/x-www-form-urlencoded` content-type.

### Fastify version
3.x.x

### Plugin version
7.1.0

**Comment by mcollina** [comment]
Unfortunately the change does not apply cleanly and tests fails. Can you send a PR against the [v7.x](https://github.com/fastify/fastify-http-proxy/tree/v7.x) branch?

> Second question, do you mind to give an example on how to integrate this with https://github.com/fastify/fastify-formbody plugin, to support application/x-www-form-urlencoded content-type.

I'm sorry but I have no time to provide custom examples for folks.

**Comment by alchristleo** [comment]
> Unfortunately the change does not apply cleanly and tests fails. Can you send a PR against the [v7.x](https://github.com/fastify/fastify-http-proxy/tree/v7.x) branch?
> 
> > Second question, do you mind to give an example on how to integrate this with https://github.com/fastify/fastify-formbody plugin, to support application/x-www-form-urlencoded content-type.
> 
> I'm sorry but I have no time to provide custom examples for folks.

I've created a PR agains v7.x branch, kindly help review https://github.com/fastify/fastify-http-proxy/pull/273 thanks
