### ISSUE TITLE
use fastify-plugin instead of patching directly the metadata

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-http-proxy#280]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We should use fastify-plugin instead of patching manually the metadata symbol.

**Comment by elxcode** [comment]
Hi @Eomm  @Uzlopak can I work on this issue ?

**Comment by Eomm** [comment]
Go for it!
