### ISSUE TITLE
Is wildcard path matching supported?

### ISSUE THREAD

**Issue by nada-one** [fastify/fastify-http-proxy#282]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hello!

I am in the process of reviewing if we can replace http-proxy-middleware with fastify-http-proxy as we're planning to move from express to fastify. One of the features that we utilize in http-proxy-middleware is wildcard path matching which allows us to append `"/*"` to the path as the value for the prefix parameter (e.g.` "/users/*"`) so we wouldn't have to register each route individually.  

Is this feature supported in fastify-http-proxy?

Thanks!

**Comment by mcollina** [comment]
I think it will work the same for you but you'll have to change how you set it up.

`@fastify/http-proxy` forwards all requests with a given prefix to the destination, there is no wildcard to set.

**Comment by nada-one** [comment]
Thanks for the feedback! Just had to tweak the setup and remove the wildcard and it now works as expected.
