### ISSUE TITLE
Is custom error logging supported?

### ISSUE THREAD

**Issue by nada-one** [fastify/fastify-http-proxy#283]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Is there an option to define custom error logging handler within fastify-http-proxy? I see that the onError hook in my fastify app catches the errors in relation to proxy requests but just wondering if there's a way to define custom logging handler within fastify-http-proxy similar to subscribing to onError event in http-proxy-middleware package.

Thanks in advance for the feedback!

**Comment by climba03003** [comment]
Please make use of `encapsulation`.

```js
fastify.register(function(fastify) {
  // here only executed in this context
  fastify.addHook('onError', function() {})
  fastify.register(fastifyHttpProxy)
})
```

**Comment by nada-one** [comment]
Thank you!
