### ISSUE TITLE
Update basePath to prefix for fastify v2

### ISSUE THREAD

**Issue by allancalix** [fastify/fastify-http-proxy#30]
basePath is deprecated in Fastify ^2 and should be replaced with prefix.

`(node:78101) Warning: basePath is deprecated. Use prefix instead. See: https://www.fastify.io/docs/latest/Server/#prefix`

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by allancalix** [comment]
Sure! Just opened a PR https://github.com/fastify/fastify-http-proxy/pull/31

**Comment by txchen** [comment]
Could you release a new version? so that we can get rid of that warning.

**Comment by mcollina** [comment]
We did, 2.0.0 is out.
