### ISSUE TITLE
Provide a possibility to validate request payload before proxying the request

### ISSUE THREAD

**Issue by kovalenp** [fastify/fastify-http-proxy#311]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to have the possibility to validate the request payload before proxying it further.

E.g.

Currently, `request.body` in preHandler is a stream

```
.register(require('@fastify/http-proxy'), {
      upstream: process.env.API,
      prefix: '/v1/:domain/:apiKey',
      rewritePrefix: '/full/:domain',
    })
```

so I can't have something like this:

```
.register(require('@fastify/http-proxy'), {
      upstream: process.env.API,
      prefix: '/v1/:domain/:apiKey',
      rewritePrefix: '/full/:domain',
      preHandelr: (req) => { validate(req.body)}
    })
```

### Motivation

I have and rpc api which I'm proxying via http-proxy. I would like to check request json payload and restrict certain methods (not to proxy it further and reply with error)

I have no possibility to do so, since request.body is not parsed in preHander.

**Comment by kovalenp** [comment]
See https://github.com/fastify/help/issues/906

**Comment by Eomm** [comment]
Thanks for reporting!
It is in the roadmap: https://github.com/fastify/fastify-http-proxy#todo

Would you like to send a Pull Request to address this feature?
