### ISSUE TITLE
how to dynamic rewrite or change proxy url, changeOrigin or other options

### ISSUE THREAD

**Issue by xygengcn** [fastify/fastify-http-proxy#329]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

```js
import Fastify from 'fastify';
import proxy from '@fastify/http-proxy';

const server = Fastify({ logger: true });

// dynamic
const proxyMap = {
    '^/test': {
        target: 'http://localhost:3001',
        rewrite: '/newtest', // http://localhost:3000/test -> http://localhost:3001/newtest
        changeOrigin: true
    },
    '^/test2': {
        target: 'http://localhost:3002',
        rewrite: '', // http://localhost:3001/test2/get -> http://localhost:3002/get
        changeOrigin: true
    }
};

server.register(proxy, {
    upstream: '',
    http2: false, // optional
    preHandler(req, reply, done) {
        done();
    },
    // Feature
    router(req, reply) {
        const find = Object.keys(proxyMap).find((key) => new RegExp(key).test(req.url));
        if (find) {
            return proxyMap[find].target;
        }
        return find;
    },
    replyOptions: {
        getUpstream(req, base) {
            console.log(req.url, base);
            const find = Object.keys(proxyMap).find((key) => new RegExp(key).test(req.url));
            if (find) {
                return proxyMap[find].target;
            }
            return '';
        }
    }
});

server.listen({ port: 3000 });
```

**Comment by mcollina** [comment]
Can you clarify the question? It seems your example implemented this already with our current options.

**Comment by xygengcn** [comment]
> Can you clarify the question? It seems your example implemented this already with our current options.

I want to have a handler that can modify the target and rewrite at runtime, for example, when I first started http://localhost:3000/test -> http://localhost:3001/newtest ；After a while, I want to make changes in runtime http://localhost:3000/test -> http://localhost:3002/newtest I don't need to restart the project. Similar to HTTP proxy middleware, there is a router function that can be implemented

**Comment by mcollina** [comment]
You can always use https://www.npmjs.com/package/@fastify/reply-from to implement whatever routing logic you want to handle.

It's likely the easiest way for you to achieve that.
