### ISSUE TITLE
Is it possible to use `preSerialization` or `onSend` hooks for fastify/http-proxy?

### ISSUE THREAD

**Issue by nducal** [fastify/fastify-http-proxy#340]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello!

While reading the documentation for `fastify/http-proxy`, I haven't found the possibility to set a `preSerialization` or `onSend` hooks for a proxy. I know I can set `onResonse` for `reply-from`, but from the fastify documentation, I have read that after this you cannot send any more data to client (i.e. when you get to onResponse, the client already got the response and this is useful only for some parsing or sending some stats etc.). 

What i want to achieve is have something like this:
```js
fastify.register(FastifyHttpProxy, {
  upstream: "http://localhost:8080",
  prefix: '/',
  http2: false,
  preHandler: preProcessRequest,
  preSerialization: preProcessResponse
})
```
where `preSerialization` would change some things in the response from the upstream (this has to be done to protect some credentials/other editing which I can't do in the upstream service).

Is there a good way to make this work as I intend it to?

**Comment by mcollina** [comment]
I don't think we are wiring those hooks.

You can achieve this by wrapping addHook and fastifyhttproxy in a encapsulating plugin.

**Comment by nducal** [comment]
Hi @mcollina! Thank you for your response. Yeah, there is no wiring for those hooks after analyzing the code for `http-proxy`. Also, could you provide a short example for encapsulating plugin? Or if there are any examples available online

**Comment by mcollina** [comment]
```js
fastify.register(async function (fastify) {
  fastify.addHook(...)
  fastify.register(require('@fastify/http-proxy', ...)
})
```

**Comment by nducal** [comment]
Oh, got it. Thank you!
