### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jamilservicos** [fastify/fastify-http-proxy#37]
change

`fastify.addContentTypeParser('application/json', bodyParser);`

to

```
if (!fastify.hasContentTypeParser('application/json')) {
    fastify.addContentTypeParser('application/json', bodyParser);
  }
```

**Comment by mcollina** [comment]
That was on purpose, because the rest of the logic assumes json was parsed. Why would you like to change this?

**Comment by jamilservicos** [comment]
https://www.fastify.io/docs/latest/ContentTypeParser/

> You can also use the hasContentTypeParser API to find if a specific content type parser already exists.

https://github.com/fastify/fastify/blob/2835df26e9d17b0b5eab1a49d6eb08fdd412ca00/lib/contentTypeParser.js

line 36 at 38:
```
if (this.hasParser(contentType)) {
    throw new FST_ERR_CTP_ALREADY_PRESENT(contentType)
 }
```
https://github.com/fastify/fastify/blob/a584210d9a3d6d60c00232290aeeda749f58d3b1/lib/errors.js

line 15:

`createError('FST_ERR_CTP_ALREADY_PRESENT', `Content type parser '%s' already present.`)`

to avoid this error, it is best to check if it already exists. As recommended in the documentation.

**Comment by mcollina** [comment]
That error should not happen, as the content type parser should be encapsulated. Which version of Fastify are you using?

Can you please upload an example to reproduce?

**Comment by jamilservicos** [comment]
This error has already happened to me, so I analyzed the code I made this change and it worked perfectly.
tomorrow if I have a free time, I create a sample app with the error and make print screens

**Comment by mcollina** [comment]
It’s easier if you put it in a repo, or if you send a PR.

**Comment by Mikescops** [comment]
Hello,

This error is hapenning to me, it depends on how I register my plugins.

Scenario is with this versions:
```
        "@fastify/http-proxy": "^11.0.0",
         "fastify": "^5.1.0",
        "fastify-raw-body": "^5.0.0"
```

If I fastify.require fastify-raw-body before http-proxy I get `FastifyError: Content type parser 'application/json' already present.`.

If I do the opposite it works.

All this happens during the setup hook.
