### ISSUE TITLE
information : 

### ISSUE THREAD

**Issue by matth-c3** [fastify/fastify-http-proxy#42]
Hello, 

As we registerer the proxy to fastify, can I do some logic ( addHook ) in the fastify instance before providing it to fastify-http-proxy ? 

On description of [onRequest](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md)  and [Hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) in fastify documentation I see that I could do it on that `method`, Is it doable instead of doing it in the preHandler of the proxy ?
Same for helmet, cors, can I set it on this fastify instance ?

For example for the JWT, I use the JWT-encrypt to add additional informations (extra Authorization) in the token ( encrypted ). As all the backend is using http/2 it's not really necessary to have the data encrypted in the bearer token.

Something like : 

-- public --> proxy ( set CORS, helmet, authentication/jwt,...) --> backend 

Thanks by advance.

**Comment by mcollina** [comment]
Yes you should be able to, let us know if you run into any issues!

**Comment by matth-c3** [comment]
Hello @mcollina ok thanks. 

Last question regarding HTTP/2 | HTTP and | wss : 

I can read in the [HTTP/2 support](https://github.com/fastify/fastify/blob/master/docs/HTTP2.md) the following : 

> ALPN negotiation allows to support both HTTPS and HTTP/2 over the same socket. Node core req and res objects can be either HTTP/1 or HTTP/2. Fastify supports this out of the box:

Would it mean that on the proxy level, I could also route wss accordingly ? Or it would be better to use a different endpoint for the WSS ? 

As I use SSL/TLS over WS, I'm wondering if I could forward the request to the backend server too as `HTTP/1` would be allowed/interpreted on proxy level. 

Thanks.

**Comment by mcollina** [comment]
fastify-http-proxy does not proxy websockets. It would be amazing to add the support for it. Would you like to send a PR?

**Comment by matth-c3** [comment]
Hello @mcollina , 

I'm not sure to understand, you mean to be able to route ws directly from fastify-http-proxy by attaching ws client and route accordingly by connecting to a ws server ?

Thanks

**Comment by mcollina** [comment]
Basically "upgraded" requests are out of the fastify logic. So they would need to be handled separately.

**Comment by matth-c3** [comment]
@mcollina , 

It should be doable, I check how it's done in http-proxy modules it should take 2 or 3 days to implement. 

At the moment I use socketCluster, it's based on websocket but I would need to try.

Quick question here, I'm doing some kind of API gateway, what's the good side of using fastify-proxy instead of doing 302 (`.redirect(..)`) ?

Thanks.

**Comment by mcollina** [comment]
I don't understand the question.

**Comment by matth-c3** [comment]
@mcollina no need ...  

I will get back to the support of websocket when I'm done for my project.

For now I will manage the 'upgrade' in the backend ( not on proxy level / or reverse proxy like nginx ) and leave the WS connection going to a different endpoint.

Thanks for your really quick answer :)
