### ISSUE TITLE
Modify headers

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-http-proxy#44]
I am investigating using this module to create a service proxy. In this proxy I will need to be able to inspect and modify or add headers to the request. My testing reveals that I can _add_ headers, but I do not seem to be able to _modify_ headers.

```js
    preHandler(req, res, next) {
      const apiKey = req.headers['x-api-key']
      if (!apiKey) {
        return res.code(400).send({invalid: 'request'})
      }
      const bar = req.headers['x-bar']
      if (bar) {
        req.headers['bar'] = 'bar;modified'
      }

      req.headers['x-foo'] = 'foo'
      next()
    }
```

If you add that `preHandler` to the `example.js` included in this repository and attempt to send a request with a `x-bar` header then the "upstream" service does not see the modified header. It sees the original unaltered header.

Are there plans to support header manipulation in this manner?

**Comment by mcollina** [comment]
Definitely. This module is looking for more contributions! ;)

**Comment by jsumners** [comment]
Closing this for now. I think my test case was bogus. I am not seeing this behavior in my actual usage. If it comes back up, I'll address it then.

**Comment by KaKi87** [comment]
Hello,

I'm experiencing the same issue : modifying headers from `@fastify/http-proxy`'s `preHandler` hook won't work, while manually proxying (for example, using `axios`) will work.

Thanks.

**Comment by jokester** [comment]
I had a similar experience today but then I found a tricky behavior in header rewriting:

```js
app.register(require('@fastify/http-proxy'), {
  upstream: 'https://api.openai.com',
  prefix: '/openai',
  preHandler(request, reply, next) {

    // this does not work, no matter if the client sent the same header or not
    request.headers['Authorization'] = `Bearer ${process.env.OPENAI_API_KEY}`; 

    // this worked in both cases
    request.headers['authorization'] = `Bearer ${process.env.OPENAI_API_KEY}`;

    request.headers['host'] = 'api.openai.com';
    next();
  },
});
```

Cannot say this is the OP's case too. Hope this can help people from future.

**Comment by Zenyet** [comment]
> I had a similar experience today but then I found a tricky behavior in header rewriting:
> 
> ```js
> app.register(require('@fastify/http-proxy'), {
>   upstream: 'https://api.openai.com',
>   prefix: '/openai',
>   preHandler(request, reply, next) {
> 
>     // this does not work, no matter if the client sent the same header or not (note the case)
>     request.headers['Authorization'] = `Bearer ${process.env.OPENAI_API_KEY}`; 
> 
>     // this worked in both cases
>     request.headers['authorization'] = `Bearer ${process.env.OPENAI_API_KEY}`;
> 
>     request.headers['host'] = 'api.openai.com';
>     next();
>   },
> });
> ```
> 
> Cannot say this is the OP's case too. Hope this can help people from future.

thanks a lot!
