### ISSUE TITLE
How to follow redirects?

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#46]
How do I achieve that ?

**Comment by mcollina** [comment]
it doesn’t. You’ll likely have to send a PR to add support for this.

**Comment by parthibd** [comment]
Thanks for the prompt reply. I'll try to implement it :)

**Comment by gary-bluenove** [comment]
Any update on this?

**Comment by mcollina** [comment]
Would you like to implement it?

**Comment by julie-ng** [comment]
This quick and dirty example works for me

```js
fastify.register(proxy, {
    upstream: apiHost,
      prefix: '/api/',
      replyOptions: {
          onResponse: (req, reply, res) => {
              // handle redirects
              console.log(res.headers)
              if ([301, 302, 303, 307].includes(res.statusCode)) {
                  let i = res.rawHeaders.indexOf('Location')
                  if (i > -1) {
                      let location = res.rawHeaders[i + 1]
                      reply.redirect(location)
                  }
              } else {
                  reply.send(res)
              }             
          }
      }
  })
```

**Comment by mcollina** [comment]
Thanks @julie-ng! Do you think we should add that behind an option somewhere?

Note that your code has a bug - if the `Location` headers is missing, no response will be sent.

**Comment by jsumners** [comment]
According to https://tools.ietf.org/html/rfc2616#section-10.3 each of these redirect codes _should_ include a `Location` header to the desired resource, provided the original request was a `GET` request. So it's not really a bug, but an assumption of spec adherence.

**Comment by jsumners** [comment]
However, the header names should have case normalization applied because it could be `Location`, `location`, `lOcAtIoN`, or any other case variation.

**Comment by julie-ng** [comment]
@mcollina has a good point though. Ideally one should account for less than perfect downstream services ;-)

The question is whether to throw a 5xx error or pass along the response as is.
