### ISSUE TITLE
Selectively apply middleware to some specific routes

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#47]
I am using this library to create a simple api gateway for my microservices . I am using `preHandler` to check which route needs the middleware but I am quiet lost after this point . My objective is to register the middleware in certain routes in my services only . How do I achieve that ?

**Comment by mcollina** [comment]
You can’t using this module. You’d have to use fastify-reply-from directly (check the code) for the routes you need having a different preHandler

You might be able to achieve it by using a prefix and creating two or more instances of this.

**Comment by parthibd** [comment]
Thanks for the heads up . But it'll be pretty cool if it could be done in this module right ?  :)

**Comment by mcollina** [comment]
Yes! You'll need to make some changes on these: https://github.com/fastify/fastify-http-proxy/blob/master/index.js#L43-L44.

**Comment by parthibd** [comment]
I'll check it out . Will make a PR when done .
