### ISSUE TITLE
How to route all the requests from all the proxies through a common middleware

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#48]
How do I proxy all the request from all the proxies through a common middleware before they are are finally sent ?

**Comment by Eomm** [comment]
Hi,
I think you can do it configuring an [`onSend`](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#the-onsend-hook) hook in the root instance of fastify, so all your plugins and routes will execute that hook

**Comment by parthibd** [comment]
Thanks a lot for the tip :)
