### ISSUE TITLE
How to properly handle files like css,js .etc

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#49]
How to properly handle files like js,css,images and stuff relative to the proxy endpoint since these files returned are relative to the proxy itself not the endpoint ?

**Comment by Eomm** [comment]
I'll try to do an example to understand:

```
<img src="./hello/world.png" />
=> HTTP GET to https://example.com/my-fastify-proxy/hello/world.png

proxy redirect the request to https://other-endpoint.com/whatelse/hello/world.png
and reply
```

I don't get where the workflow brakes, could you specify a use case?

**Comment by parthibd** [comment]
Here 

```js
const server = require('fastify')();
const proxy = require('fastify-http-proxy');

server.register(proxy, {
    upstream: "http://localhost:8080",
    prefix: '/tracking',
    http2: false,
});

(async () => {
    await server.listen(3000);
})();
```

**Comment by parthibd** [comment]
Say I call localhost:3000/tracking , the files are returned relative to http://localhost:3000/tracking/app.min.js . How do I resolve this ?

**Comment by parthibd** [comment]
Also the files in the upstream server are relative to root . Could this be the problem ?

**Comment by mcollina** [comment]
Are the files being served if you fetch them directly?
In case.. yes it's definitely that those a relative urls.

**Comment by parthibd** [comment]
Yes. They work just fine if I access it directly from the upstream endpoint. What's going wrong?

**Comment by parthibd** [comment]
Yes those files are relative urls like `/app.min.js`
