### ISSUE TITLE
TODO: Generate unique request ids and implement request tracking

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-http-proxy#5]
To support request tracking will the below code is sufficient:
```javascript
function reply (request, reply) {
    request.req.headers[<requestIdHeaderName>] = request.id;
    var dest = request.req.url.replace(this.basePath, '')
    reply.from(dest)
}
```
Please let me know. I'll submit pull request.

**Comment by mcollina** [comment]
I would prefer not to edit the original headers.

**Comment by nileshmali** [comment]
So what would be the plan to support this feature?
Or should this be coming from fastify itself?

**Comment by mcollina** [comment]
It needs to be implemented in fastify-reply-from. I've tried to explain what I mean in https://github.com/fastify/fastify-reply-from/issues/7#issuecomment-384191854.

Basically in https://github.com/fastify/fastify-reply-from/blob/master/index.js#L66 we should add the new header. Side note, we should really create a copy of that object before manipulating it.
