### ISSUE TITLE
Subdirectory after root path in upstream endpoint gives 404

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#50]
I am having a path problem. The site works fine in apache. My site is like this `http://localhost/mysite`. So if I set my prefix to `/proxy` it should route to `http://localhost/mysite`. Instead it gives 404. Why is this happening?

**Comment by parthibd** [comment]
Btw I'm trying to access my site through the proxy like this `http://localhost/proxy`. What's going on?

**Comment by geewrd** [comment]
Your example configuration would be helpful to know for sure, but I think you want to use the `rewritePrefix` option, like so:
```js
  fastify.register(require('fastify-http-proxy'), {
    upstream: 'http://localhost',
    rewritePrefix: 'mysite,
    prefix: '/proxy'
  })
```
I'm not sure why the documentation has an example where the upstream is `'http://single-signon.example.com/auth'` when the path is ignored.
