### ISSUE TITLE
Proxy S3 storage file through fastify-http-proxy

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-http-proxy#53]
I am thinking of writing a thin proxy layer using this library to proxy files stored in AWS S3 . I want to know will there be any major latency besides the usual to stream through fastify-http-proxy ?

**Comment by jsumners** [comment]
No. Processing is minimal.

**Comment by parthibd** [comment]
That sounds great ! Thanks a lot for the prompt reply :)
