### ISSUE TITLE
Need documentation for alternative for http-proxy

### ISSUE THREAD

**Issue by mhf-ir** [fastify/fastify-http-proxy#60]
I think if documentation will be better could take users from [http-proxy](https://github.com/nodejitsu/node-http-proxy) to `fastify-http-proxy`.

Take a look of dead package and it's users:

Current usage and starts and issue and holding pull requests:
![Screenshot from 2019-06-19 06-28-33](https://user-images.githubusercontent.com/1172526/59731478-8a363b80-925b-11e9-9550-ff51f320f23e.png)

Look:
https://github.com/nodejitsu/node-http-proxy/issues/1341

* Work with default node http
* Events, timeout
* Same example of http-proxy

**Comment by mcollina** [comment]
Would you like to send some PRs?

**Comment by mhf-ir** [comment]
I will try to test some needed feature, to check alternative way.

**Comment by Eomm** [comment]
Yeah, it would be constructive if you open an issue for each feature that is missing to archive a more complete plugin and alternative to that module

**Comment by mhf-ir** [comment]
After little try i think it's fastify independent use case, It's actual pure node.js. default http module.
I'm not quite sure.
