### ISSUE TITLE
How to read the response data?

### ISSUE THREAD

**Issue by eduardobc88** [fastify/fastify-http-proxy#65]
Hi! I have a doubt. How to I read the response data? It is possible? Thank's
```
...
replyOptions: {
      onResponse (req, reply, res) {
        console.log('== onResponse - data ==', res.response.data) // example
        reply.send(res)
      },
    },
...
```

**Comment by mcollina** [comment]
`res`  is the response stream from the origin. You'll need to parse the response yourself.

**Comment by eduardobc88** [comment]
Thank you for response!
Yes, only that I didn't know where is the 'data' to parse and finally I did it with:
```
res.on('data', async (data) => {
  // code
})
res.on('end', async () => {
  // code
})
```

**Comment by mcollina** [comment]
You should not mix async functions and event emitters. You are likely creating a memory leak because there is no one “catching” if that throws.

**Comment by WhereJuly** [comment]
@mcollina Hello.

I was also struggling finding the `res` API. Arrived to the following [solution](https://gist.github.com/WhereJuly/f4911312e46d56567a8192710a008705). Do you think it is good for a PR to readme?
