### ISSUE TITLE
Use new fastify-reply-from 1.1.0

### ISSUE THREAD

**Issue by kraf** [fastify/fastify-http-proxy#70]
The newest `fastify-http-proxy` version on NPM still uses `fastify-reply-from` 0.6.x. From the commits it looks safe to update `fastify-http-proxy` to use the newer 1.x versions.

Would it be possible to update on your end? We're currently using the master branch in our `package.json` :smile:

**Comment by Eomm** [comment]
Thanks to pointed it out 👍
[v2.3.0 out](https://github.com/fastify/fastify-http-proxy/releases/tag/v2.3.0)
