### ISSUE TITLE
Unique request ids and request tracking

### ISSUE THREAD

**Issue by vorillaz** [fastify/fastify-http-proxy#80]
## 🚀 Feature Proposal

There is TODO note at the very end of the `README.md` about creating unique request ids and implementing request tracking. I am highly interested in this feature and if some of the maintainers could drop an architecture overview I am more than happy to create a PR.

**Comment by mcollina** [comment]
Essentially fastify already assign an id that is unique to this process for each request. The id contained in `req.id` should be forwarded to the destination.

The header key should be configurable, by default in fastify it is https://github.com/fastify/fastify/blob/772cf5eb9fb3565f237630fb5a6790808ac07688/build/build-validation.js#L25.

We should provide a guide into how to configure a globally unique id instead, I would recommend to use http://npm.im/hyperid.
