### ISSUE TITLE
Can't access body in preHandler

### ISSUE THREAD

**Issue by MihaFriskovec** [fastify/fastify-http-proxy#86]
When using preHandler in proxy, body is not parsed but instead is overwritten with the request object.

## To Reproduce

To reproduce the behavior create a simple reverse proxy and make a POST or PUT request with a body. (JSON)

```js
fastify.register(require("fastify-http-proxy"), {
  upstream: "http://localhost:8080", 
  prefix: "/api/proxy",
  async preHandler(request, reply) {
    console.log(request.body) // This line logs whole fastify request object instead of body
    return
  }
})
```

## Expected behavior

As is preHandler hook on routes, the body should be accessible from proxy's preHandler.

Digging through code I did found a custom body-parser, which I believe disables parsing.

```js
// Code from index.js
fastify.addContentTypeParser('application/json', bodyParser)
fastify.addContentTypeParser('*', bodyParser)

function bodyParser (req, done) {
    done(null, req)
  }
```

After disabling (commenting out) contentTypeParser the preHandler is working as expected (the body is parsed and accessible).

Is that the expected behavior and if so are there any workarounds?

## Your Environment

- *node version*: 12.16.1
- *fastify version*: 2.12.1
- *os*: Linux

**Comment by amiteshtoharya4** [comment]
+1 on this... 
I was thinking if there could be an option through which the user could say if they want the ContentParser to be added or not.

Something like addContentParser which could be true by default. And the user could send it as false to stop that....

**Comment by mcollina** [comment]
+1 on the option. Would you mind to send a PR?

**Comment by Eomm** [comment]
I didn't check deeper, but this should be intended to stream the client-request directly to the proxy-request

You should be able to read the body from the `request.raw.on('data', ...)` since it is not consumed yet

**Comment by Sequoia** [comment]
+1 that this is confusing. My expectation was that after the [parsing lifecycle event](https://www.fastify.io/docs/latest/Lifecycle/), the body is parsed. It's unexpected that in a `preHandler` the body is still not parsed.

Is there a later point at which the body is **certain** to have been parsed?

**Comment by mcollina** [comment]
You need to set `proxyPayload: false` in the options.

**Comment by kovalenp** [comment]
@mcollina thank you, I can access it this way. The documentation says I need to implement `addContentTypeParser` correctly, but fastfy already provides application/json parser.

What is the approach if I want to validate payload and proxy it further?

**Comment by Uzlopak** [comment]
You have already opened an issue regarding your last question. Please stick to it and try to not defragment the support.
